bump_version: null
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-gms_16s_logo_light.png
  - docs/images/nf-core-gms_16s_logo_light.png
  - docs/images/nf-core-gms_16s_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-gms_16s_logo_light.png
  - docs/images/nf-core-gms_16s_logo_light.png
  - docs/images/nf-core-gms_16s_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: '@fwa93'
  description: A Nextflow pipeline for 16S typing of bacteria based on the EMU tool
    from treangenlab.
  force: true
  is_nfcore: false
  name: gms_16S
  org: genomic-medicine-sweden
  outdir: .
  skip_features: null
  version: v0.1.0
update: null
