bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/.dockstore.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - assets/nf-core-gms_16S_logo_light.png
    - docs/images/nf-core-gms_16S_logo_light.png
    - docs/images/nf-core-gms_16S_logo_dark.png
    - lib/*.groovy
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md
    - LICENSE
    - .prettierignore
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.max_cpus
    - params.max_memory
    - params.max_time
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  actions_ci: False
nf_core_version: 3.2.0
org_path: null
repository_type: pipeline
template:
  author: "@fwa93"
  description: A Nextflow pipeline for 16S typing of bacteria based on the EMU tool
    from treangenlab.
  force: true
  is_nfcore: false
  name: gms_16S
  org: genomic-medicine-sweden
  outdir: .
  skip_features: null
  version: v0.1.0
update: null
