name: "generate_master_html"
description: A python script that utilises jinja2 to generate a .html file containing links to all of the sample's output html files in the form of a table.
keywords:
  - Web development
  - Summary
  - HTML

tools:
  - "generate_master_html.py":
      description: "Generates master.html file"
      homepage: "https://github.com/SMD-Bioinformatics-Lund/taco/blob/main/bin/generate_master_html.py"
      documentation: "None"
      tool_dev_url: "None"
      doi: "None"
      licence: "None"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - csv:
      type: file
      description: csv file containing information regarding 16S metagenomic data
      pattern: "*.{csv}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - html:
      type: file
      description: HTML file containing table with links to sample outputs
      pattern: "*{.html}"

authors:
  - "@ryanjameskennedy"
